name: jetlagios
options:
  bundleIdPrefix: ly.hall
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  MapLibre:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    majorVersion: 6.0.0

targets:
  jetlagios:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
          - build
          - Frameworks
          - Generated
          - Preview Content
          - project.yml
          - run.nu
      - path: Generated
        optional: true
        buildPhase: sources
    dependencies:
      - package: MapLibre
      - framework: Frameworks/JetLagMobile.xcframework
        embed: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ly.hall.jetlagios
        DEVELOPMENT_TEAM: "27A879WMMJ"
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_GENERATION_MODE: GeneratedFile
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: "YES"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_INCLUDE_PATHS:
          - $(SRCROOT)/Generated
        OTHER_LDFLAGS:
          - -ljet_lag_mobile
    info:
      path: Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        UILaunchScreen:
          UIColorName: AccentColor
    resources:
      - path: Assets.xcassets
      - path: Preview Content
        optional: true
